# Generated by Django 3.2.13 on 2022-07-02 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cms_application_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=50)),
                ('applicationId', models.IntegerField()),
                ('acknowledgementNumber', models.CharField(max_length=50)),
                ('departmentId', models.IntegerField()),
                ('serviceId', models.IntegerField()),
                ('districtId', models.IntegerField()),
                ('blockId', models.IntegerField()),
                ('tahasilId', models.IntegerField()),
                ('grampanchayatId', models.IntegerField()),
                ('officeId', models.IntegerField()),
                ('applicationStatus', models.IntegerField()),
                ('appealStatus', models.IntegerField()),
                ('revisionStatus', models.IntegerField()),
                ('applicantName', models.CharField(max_length=40)),
                ('applicantAddress', models.CharField(max_length=100)),
                ('applicantPhoneNo', models.BigIntegerField()),
                ('applicationReceivedDate', models.DateField()),
                ('lastDate', models.DateField()),
                ('deliveryStatus', models.CharField(max_length=10)),
                ('deliveryDate', models.DateField()),
                ('rejectedReason', models.CharField(max_length=20)),
                ('applyMode', models.CharField(max_length=20)),
                ('designatedOfficerName', models.CharField(max_length=40)),
                ('designatedOfficerId', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('creatd_date', models.CharField(default=datetime.date(2022, 7, 2), max_length=50)),
                ('created_time', models.CharField(default='17:27:40', max_length=50)),
                ('updated_date', models.CharField(default=datetime.date(2022, 7, 2), max_length=50)),
                ('updated_time', models.CharField(default='17:27:40', max_length=50)),
            ],
            options={
                'db_table': 'cms_application_2',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceId', models.IntegerField()),
                ('serviceName', models.CharField(max_length=200)),
                ('departmentId', models.IntegerField()),
                ('departmentName', models.CharField(max_length=200)),
                ('designatedOfficer', models.IntegerField()),
                ('appellateAuthority', models.IntegerField()),
                ('revisionalAuthority', models.IntegerField()),
                ('timeLimit', models.CharField(max_length=100)),
                ('apiKey', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=300)),
                ('ipAddress', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('createdDate', models.CharField(max_length=50)),
                ('createdTime', models.CharField(max_length=50)),
                ('updatedDate', models.CharField(max_length=50)),
                ('updatedTime', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
